# This CloudFormation template is designed to automate the creation of an IAM role
# that allows a specific Lambda function to access a DynamoDB table. It defines
# the parameters needed to specify the ARN of the Lambda function's role and the
# ARN of the DynamoDB table. The template includes a single resource, an IAM role,
# that the Lambda function can assume to perform various actions on the specified
# DynamoDB table.

AWSTemplateFormatVersion: '2010-09-09'
Description: Automatically Create DynamoDb Role for Lambda function to assume
Parameters:
  AutoStopLambdaFunctionRoleArn:
    Description: Enter the ARN of the role applied to the AutoStopEC2 Lambda function
    Type: String
  DynamoDBTableArn:
    Description: Enter the ARN of the DynamoDB table that the AutoStop Lambda function will access
    Type: String

Resources:
  CrossAccountRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Ref AutoStopLambdaFunctionRoleArn
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "DynamoDBAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                Resource: !Sub "${DynamoDBTableArn}"
